create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 5 and 254),
  company text check (company is null or char_length(company) <= 120),
  subject text check (subject is null or char_length(subject) <= 160),
  message text not null check (char_length(message) between 10 and 3000),
  status text not null default 'new' check (status in ('new', 'read', 'replied'))
);

alter table public.contact_submissions enable row level security;

revoke all on table public.contact_submissions from anon, authenticated;
grant insert on table public.contact_submissions to anon;
grant select, update, delete on table public.contact_submissions to authenticated;
grant usage, select on sequence public.contact_submissions_id_seq to anon, authenticated;

create policy "Visitors can submit contact messages"
on public.contact_submissions
for insert
to anon
with check (status = 'new');

create policy "Resume owner can view contact messages"
on public.contact_submissions
for select
to authenticated
using ((select auth.jwt() ->> 'email') = 'nguyetninh0310@gmail.com');

create policy "Resume owner can update contact messages"
on public.contact_submissions
for update
to authenticated
using ((select auth.jwt() ->> 'email') = 'nguyetninh0310@gmail.com')
with check ((select auth.jwt() ->> 'email') = 'nguyetninh0310@gmail.com');

create policy "Resume owner can delete contact messages"
on public.contact_submissions
for delete
to authenticated
using ((select auth.jwt() ->> 'email') = 'nguyetninh0310@gmail.com');

create index if not exists contact_submissions_created_at_idx
on public.contact_submissions (created_at desc);

